### ISSUE TITLE
Instalador Windows - Varios

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-app#153]
Hoy tenemos un instalador (nsis) que es medio viejín. Y a lo largo del tiempo tuvimos varios reportes de errores con este instalador. 
Consideraría revisarlo y retomar estos detalles:

- [ ] Viejo issue: https://github.com/Program-AR/pilas-bloques-ember/issues/321 Firma del instalador para no necesitar poner "confío en este software" al instalar
- [ ] Viejo issue: https://github.com/Program-AR/pilas-bloques-ember/issues/286 Doble click en uno de los archivos de PB debería abrir la app y pasar por parámetro el archivo, y Pilas Bloques decidir qué hacer.
- [ ] Viejo issue: https://github.com/Program-AR/pilas-bloques-ember/issues/82 Problemas referidos al cambio de la carpeta default de instalación
- [ ] Viejo issue: https://github.com/Program-AR/pilas-bloques-ember/issues/537 Cambiar la carpeta por default de instalación a algo por default
- [ ] Viejo issue: https://github.com/Program-AR/pilas-bloques-ember/issues/543 El desintalador no funciona

**Comment by rgonzalezt** [comment]
Se encara en https://github.com/Program-AR/pilas-bloques-app/issues/173
