### ISSUE TITLE
Epic: Preview Toolbox Parte II: la venganza

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-app#218]
Depende de
- [x] Program-AR/pilas-bloques-ember#1300 

Issues:
- [x] https://github.com/Program-AR/pilas-bloques/issues/1444
- [ ] https://github.com/Program-AR/pilas-bloques/issues/1445
- [x] https://github.com/Program-AR/pilas-bloques/issues/1446
- [ ] https://github.com/Program-AR/pilas-bloques/issues/1447

**Comment by asanzo** [comment]
Cierro, subissues ya encarados.
