### ISSUE TITLE
Blockly - Traerse los bloques

### ISSUE THREAD

**Issue by tfloxolodeiro** [Program-AR/pilas-bloques-app#220]
![Image](https://github.com/Program-AR/pilas-bloques-app/assets/5421992/ac0208ce-eada-4a12-930e-fbbf6b16f125)

- Objetivo: Probar en el Toolbox Preview del creador.
- Poner foco en la parte visual de los bloques
- Al sentarse a hacerlo, puede que surja la idea de separarlo en más de un PR, eso es válido.

```[tasklist]
### Tasks
- [x] Mirar con los ojos finitos desde lejos lo necesario, ver el [diseño que propuso Tom](https://github.com/Program-AR/pilas-bloques-app/blob/develop/src/blockly.ts) y pensar cómo se completa eso mirando [blocks-gallery](https://github.com/Program-AR/pilas-bloques-ember/blob/develop/app/services/blocks-gallery.js) de Ember..
- [x] Traerse todos los bloques que estén creados con los helpers `crearBloqueAccion`, `crearBloqueSensor` y `crearBloqueValor`. Tom ya empezó: `crearBloqueAcción` se lo trajo a `createPrimitiveBlock`
- [x] No incluiría los aliases, no copiemos ese feature porque yo no lo usaría más, es tiempo que deprequemos los bloques viejos.
- [x] En el toolbox, respetar el orden de las categorías de Ember.
- [x] Todo tiene que estar internacionalizado para que después podamos completar las traducciones. Traerse las que existen.
- [x] No traerse bloques viejos
- [x] Incluír también la posibilidad de crear bloques custom y traerse esos (como los de alternativa, repetición, etc.)
- [x] Deprecar [ember-blockly](https://github.com/Program-AR/ember-blockly/blob/master/addon/components/ember-blockly.js) (leer un toque a ver si nos olvidamos algo)
- [ ] https://github.com/Program-AR/pilas-bloques-app/issues/248
- [ ] Tests: Todos los bloques deberían poder renderizarse. O sea, quizás iterar por todos los bloques existentes del creador, y meterlos en un workspace? o un workspace enorme con todos los bloques?
- [ ] Revisar ember si no hay tests asociados que podamos sacar
- [ ] https://github.com/Program-AR/pilas-bloques-app/issues/249
```

En un principio pateamos los botones de importar/exportar solución, y los de sugerencias.
